\documentclass{article}
\author{Ben Kandel}
\title{Simulation experiments for sparse regression}
\begin{document}
\maketitle
<<initial, results='hide'>>=
require(ANTsR)
@ 

Now we initialize some data: 
<<generate, results='hide'>>=
mat.size <- 10
nsubjects <- 1000
noise.signal <- 0.5
noise.image <- 0.5
mymat <- array(rep(0, mat.size * mat.size * mat.size * nsubjects), 
               dim=c(mat.size, mat.size, mat.size, nsubjects))
signal.1 <- runif(nsubjects)
signal.2 <- runif(nsubjects) 
outcome <-  3 + signal.1 +  signal.2 + rnorm(nsubjects, sd=noise.signal) 
plot(signal.1, outcome, xlab='signal.1', ylab='outcome')
plot(signal.2, outcome, xlab='signal.2', ylab='outcome')
@ 
The correlation between the signals is: 
<<>>=
cor.test(signal.1, outcome)
cor.test(signal.2, outcome)
cor.test(signal.1+signal.2, outcome)
@
Analysis of images: 
<<results='hide'>>=
for ( i in 1:nsubjects){
  mymat[, , , i] <- abs(rnorm(mat.size * mat.size * mat.size, sd=noise.image))
  mymat[3:4, 3:4, 3:4, i] <- signal.1[i] + rnorm(8, sd=noise.image)
  mymat[(mat.size-3):(mat.size-2), 3:4, 
        3:4, i] <- signal.2[i] + rnorm(8, sd=noise.image)
}
true.mat <- array(rep(0, mat.size * mat.size * mat.size), dim=c(mat.size, mat.size, mat.size))
true.mat[3:4, 3:4, 3:4] <- 1
true.mat[(mat.size-3):(mat.size-2), 3:4, 3:4] <- 1
antsImageWrite(as.antsImage(true.mat), 'true.nii.gz')
pval.mat <- array(rep(NA, mat.size * mat.size * mat.size), dim=c(mat.size, mat.size, mat.size))
for ( i in 1:mat.size ){
  for( j in 1:mat.size){
    for (k in 1:mat.size) {
      mytest <- cor.test(mymat[i, j, k, ], outcome)
      pval.mat[i, j, k] <- mytest$p.value
    }
  }
}
pval.mat.adj <- array(p.adjust(pval.mat, "fdr"), dim=c(mat.size, mat.size, mat.size))
antsImageWrite(as.antsImage(pval.mat.adj), 'pvals.nii.gz')
plotANTsImage(as.antsImage(pval.mat.adj), slices="1x10x2")
plotANTsImage(as.antsImage(true.mat), slices="1x10x2")
@ 

<<results='hide'>>=
for(i in 1:nsubjects){
  antsImageWrite(as.antsImage(mymat[, , ,  i]), paste('img', sprintf('%.03d', i), 
                                                   '.nii.gz', sep=''))
}
write.csv(data.frame(outcome=outcome), 'demog.csv', row.names=F)
mymask <- array(rep(1, mat.size * mat.size * mat.size), dim=c(mat.size, mat.size, mat.size))
antsImageWrite(as.antsImage(as.array(mymask)), 'mask.nii.gz')
antsImageWrite(as.antsImage(matrix(mymat, nrow=nsubjects, byrow=T)), 'inmat.nii.gz')
system("./run_sccan.sh")
@ 
Now, if we projected the data into an appropriate multivariate space, we would see the true correlation: 
<<>>=
mymat.proj <- apply(mymat, 4, function(x) x %*% true.mat)
cor.test(mymat.proj, signal.1 + signal.2)
cor.test(mymat.proj, outcome)
for ( i in c(0,2)){
  myimg <- antsImageRead(paste('outView1vec00', i, '.nii.gz', sep=''), dim=3vi )
  plotANTsImage(myimg, slices="1x10x2")
}


# mydecom <- sparseRegression( matrix(mymat, nrow=nsubjects, byrow=TRUE), 
#         demog=data.frame(outcome=outcome), outcome="outcome", mask=as.antsImage(mymask), 
#                              nvecs=8)
# for( i in 1:8){
#   antsImageWrite(mydecom$eigenanatomyimages[[i]], paste('outvec', i, '.nii.gz', sep=''))
# }
@
\end{document}